accumulate_grad_batches: 1
amp: false
audio_num_mel_bins: 80
audio_sample_rate: 16000
base_config:
- egs/egs_bases/tts/fs2_adv.yaml
- egs/datasets/audio/emotion/base_text2mel.yaml
binarization_args:
  reset_phone_dict: true
  reset_word_dict: true
  shuffle: true
  trim_eos_bos: false
  trim_sil: false
  with_align: true
  with_f0: true
  with_f0cwt: false
  with_linear: false
  with_spk_embed: true
  with_spk_id: true
  with_txt: true
  with_wav: true
  with_word: true
binarizer_cls: data_gen.tts.base_binarizer_emotion.EmotionBinarizer
binary_data_dir: data/binary/training_set
check_val_every_n_epoch: 10
clip_grad_norm: 1
clip_grad_value: 0
conv_use_pos: false
crop: false
cwt_add_f0_loss: false
cwt_hidden_size: 128
cwt_layers: 2
cwt_loss: l1
cwt_std_scale: 0.8
debug: false
dec_dilations:
- 1
- 1
- 1
- 1
dec_ffn_kernel_size: 9
dec_inp_add_noise: false
dec_kernel_size: 5
dec_layers: 4
dec_num_heads: 2
decoder_rnn_dim: 0
decoder_type: fft
dict_dir: ''
disc_hidden_size: 128
disc_interval: 1
disc_lr: 0.0001
disc_norm: in
disc_reduction: stack
disc_start_steps: 0
disc_win_num: 3
discriminator_grad_norm: 1
discriminator_optimizer_params:
  eps: 1.0e-06
  weight_decay: 0.0
discriminator_scheduler_params:
  gamma: 0.5
  step_size: 60000
dropout: 0.05
ds_workers: 2
dur_enc_hidden_stride_kernel:
- 0,2,3
- 0,2,3
- 0,1,3
dur_loss: mse
dur_predictor_kernel: 3
dur_predictor_layers: 2
emotion_encoder_path: checkpoints/Emotion_encoder.pt # set the emotion encoder path
enc_dec_norm: ln
enc_dilations:
- 1
- 1
- 1
- 1
enc_ffn_kernel_size: 9
enc_kernel_size: 5
enc_layers: 4
encoder_K: 8
encoder_type: fft
endless_ds: true
ffn_act: gelu
ffn_hidden_size: 1024
ffn_padding: SAME
fft_size: 1024
fmax: 7600
fmin: 80
forcing: 20000
frames_multiple: 1
gen_dir_name: ''
generator_grad_norm: 5.0
griffin_lim_iters: 60
hidden_size: 256
hop_size: 256
infer: false
lambda_commit: 0.25
lambda_energy: 0.1
lambda_f0: 1.0
lambda_mel_adv: 0.1
lambda_ph_dur: 0.1
lambda_sent_dur: 1.0
lambda_uv: 1.0
lambda_word_dur: 1.0
layers_in_block: 2
load_ckpt: ''
loud_norm: false
lr: 1.0
max_epochs: 1000
max_frames: 1548
max_input_tokens: 1550
max_sentences: 100000
max_tokens: 30000
max_updates: 300000
max_valid_sentences: 1
max_valid_tokens: 60000
mel_disc_hidden_size: 128
mel_gan: true
mel_hidden_size: 256
mel_loss: ssim:0.5|l1:0.5
mel_vmax: 1.5
mel_vmin: -6
min_frames: 128
min_level_db: -100
nVQ: 128
noise_scale: 0.8
num_ckpt_keep: 2
num_heads: 2
num_sanity_val_steps: -1
num_spk: 500
num_test_samples: 72
num_valid_plots: 10
optimizer_adam_beta1: 0.5
optimizer_adam_beta2: 0.999
out_wav_norm: false
pitch_ar: false
pitch_embed_type: 0
pitch_enc_hidden_stride_kernel:
- 0,2,5
- 0,2,5
- 0,2,5
pitch_extractor: parselmouth
pitch_loss: l1
pitch_norm: standard
pitch_ssim_win: 11
pitch_type: frame
post_glow_hidden: 128
post_glow_kernel_size: 3
post_glow_n_block_layers: 3
post_glow_n_blocks: 8
post_share_cond_layers: false
pre_align_args:
  allow_no_txt: false
  denoise: false
  sox_resample: false
  sox_to_wav: false
  trim_sil: false
  txt_processor: en
  use_tone: true
pre_align_cls: egs.datasets.audio.emotion.pre_align.EmoPreAlign
predictor_dropout: 0.5
predictor_grad: 1.0
predictor_hidden: -1
predictor_kernel: 5
predictor_layers: 2
preprocess_args:
  add_eos_bos: true
  mfa_group_shuffle: false
  mfa_offset: 0.02
  nsample_per_mfa_group: 1000
  reset_phone_dict: true
  reset_word_dict: true
  save_sil_mask: true
  txt_processor: en
  use_mfa: true
  vad_max_silence_length: 12
  wav_processors: []
  with_phsep: true
preprocess_cls: egs.datasets.audio.libritts.pre_align.LibrittsPreAlign
pretrain_fs_ckpt: ''
print_nan_grads: false
processed_data_dir: data/processed/emotion
profile_infer: false
raw_data_dir: data/raw/ESD
ref_audio: ''
ref_hidden_stride_kernel:
- 0,3,5
- 0,3,5
- 0,2,5
- 0,2,5
- 0,2,5
ref_level_db: 20
ref_norm_layer: bn
rename_tmux: true
rerun_gen: false
resume_from_checkpoint: 0
save_best: false
save_codes: []
save_f0: false
save_gt: true
scheduler: rsqrt
seed: 1234
share_wn_layers: 4
sigmoid_scale: false
sil_add_noise: false
sort_by_len: true
task_cls: modules.GenerSpeech.task.generspeech.GenerSpeechTask
tb_log_interval: 100
test_ids: []
test_input_dir: ''
test_num: 200
test_set_name: test
text: ''
train_set_name: train
train_sets: ''
use_cond_disc: false
use_emotion: true
use_energy_embed: false
use_gt_dur: false
use_gt_f0: false
use_latent_cond: true
use_pitch_embed: true
use_pos_embed: true
use_ref_enc: false
use_spk_embed: true
use_spk_id: false
use_split_spk_id: false
use_txt_cond: true
use_uv: true
use_var_enc: false
use_word: true
vae_dropout: 0.0
val_check_interval: 2000
valid_infer_interval: 10000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_set_name: valid
var_enc_vq_codes: 64
vocoder: hifigan
vocoder_ckpt: checkpoints/trainset_hifigan
vocoder_denoise_c: 0.0
vq_start: 20500
warmup_updates: 2000
weight_decay: 0
win_size: 1024
word_size: 30000
work_dir: checkpoints/GenerSpeech
