base_config: ./transformer_tts.yaml
pre_align_args:
  trim_sil: true
binarization_args:
  shuffle: true
  with_txt: true
  with_wav: false
  with_align: false
  with_spk_embed: false
  with_f0: false
  with_f0cwt: false
num_spk: 9999999
binarizer_cls: data_gen.asr.asr_binarize.ASRBinarizer
strides: [ 2,2,1 ]
enc_ffn_kernel_size: 15
encoder_hidden_size: 256

model_type: trans
# for LSTM decoder
decoder_hidden_size: 512
decoder_rnn_dim: 512
p_attention_dropout: 0.05
p_decoder_dropout: 0.05
attention_rnn_dim: 512
attention_dim: 256
attention_location_n_filters: 16
attention_location_kernel_size: 15

max_frames: 3000
enc_layers: 8
dec_layers: 4
dec_ffn_kernel_size: 1
max_tokens: 40000
max_updates: 400000
